// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://www.reqnroll.net/).
//      Reqnroll Version:2.0.0.0
//      Reqnroll Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace FlinkDotNet.Aspire.IntegrationTests.Features
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class ObservabilityMessagesPerSecondMetricsFeature : object, Xunit.IClassFixture<ObservabilityMessagesPerSecondMetricsFeature.FixtureData>, Xunit.IAsyncLifetime
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "Features", "Observability Messages Per Second Metrics", "  As a system administrator\n  I want to monitor messages-per-second metrics acros" +
                "s all layers\n  So that I can ensure system performance and troubleshoot bottlene" +
                "cks", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags);
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "ObservabilityMetrics.feature"
#line hidden
        
        public ObservabilityMessagesPerSecondMetricsFeature(ObservabilityMessagesPerSecondMetricsFeature.FixtureData fixtureData, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
        }
        
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        async global::System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
        {
            try
            {
                await this.TestInitializeAsync();
            }
            catch (System.Exception e1)
            {
                try
                {
                    ((Xunit.IAsyncLifetime)(this)).DisposeAsync();
                }
                catch (System.Exception e2)
                {
                    throw new System.AggregateException("Test initialization failed", e1, e2);
                }
                throw;
            }
        }
        
        async global::System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Validate Kafka Producer Messages Per Second Metrics")]
        [Xunit.TraitAttribute("FeatureTitle", "Observability Messages Per Second Metrics")]
        [Xunit.TraitAttribute("Description", "Validate Kafka Producer Messages Per Second Metrics")]
        [Xunit.TraitAttribute("Category", "observability")]
        [Xunit.TraitAttribute("Category", "metrics")]
        [Xunit.TraitAttribute("Category", "kafka")]
        [Xunit.TraitAttribute("Category", "flink")]
        [Xunit.TraitAttribute("Category", "temporal")]
        [Xunit.TraitAttribute("Category", "flow")]
        public async global::System.Threading.Tasks.Task ValidateKafkaProducerMessagesPerSecondMetrics()
        {
            string[] tagsOfScenario = new string[] {
                    "observability",
                    "metrics",
                    "kafka",
                    "flink",
                    "temporal",
                    "flow"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Validate Kafka Producer Messages Per Second Metrics", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 7
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 8
    await testRunner.GivenAsync("LocalTesting infrastructure is running with observability enabled", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 9
    await testRunner.WhenAsync("I produce 1000 messages to Kafka topic \"observability-test-input\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 10
    await testRunner.ThenAsync("Kafka producer messages per second metrics should be greater than 0", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 11
    await testRunner.AndAsync("Prometheus should be able to scrape all observability metrics", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Validate Flink Job Processing Rate Metrics")]
        [Xunit.TraitAttribute("FeatureTitle", "Observability Messages Per Second Metrics")]
        [Xunit.TraitAttribute("Description", "Validate Flink Job Processing Rate Metrics")]
        [Xunit.TraitAttribute("Category", "observability")]
        [Xunit.TraitAttribute("Category", "metrics")]
        [Xunit.TraitAttribute("Category", "flink")]
        [Xunit.TraitAttribute("Category", "processing")]
        public async global::System.Threading.Tasks.Task ValidateFlinkJobProcessingRateMetrics()
        {
            string[] tagsOfScenario = new string[] {
                    "observability",
                    "metrics",
                    "flink",
                    "processing"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Validate Flink Job Processing Rate Metrics", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 14
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 15
    await testRunner.GivenAsync("LocalTesting infrastructure is running with observability enabled", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 16
    await testRunner.WhenAsync("I produce 500 messages to Kafka topic \"flink-input-test\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 17
    await testRunner.AndAsync("I start a Flink job to process messages", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 18
    await testRunner.ThenAsync("Flink job processing rate metrics should be recorded", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 19
    await testRunner.AndAsync("Prometheus should be able to scrape all observability metrics", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Validate Temporal Workflow Execution Rate Metrics")]
        [Xunit.TraitAttribute("FeatureTitle", "Observability Messages Per Second Metrics")]
        [Xunit.TraitAttribute("Description", "Validate Temporal Workflow Execution Rate Metrics")]
        [Xunit.TraitAttribute("Category", "observability")]
        [Xunit.TraitAttribute("Category", "metrics")]
        [Xunit.TraitAttribute("Category", "temporal")]
        [Xunit.TraitAttribute("Category", "workflows")]
        public async global::System.Threading.Tasks.Task ValidateTemporalWorkflowExecutionRateMetrics()
        {
            string[] tagsOfScenario = new string[] {
                    "observability",
                    "metrics",
                    "temporal",
                    "workflows"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Validate Temporal Workflow Execution Rate Metrics", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 22
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 23
    await testRunner.GivenAsync("LocalTesting infrastructure is running with observability enabled", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 24
    await testRunner.WhenAsync("I execute Temporal workflows", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 25
    await testRunner.ThenAsync("Temporal workflow execution rate metrics should be recorded", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 26
    await testRunner.AndAsync("Prometheus should be able to scrape all observability metrics", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Validate End-to-End Flow Rate Metrics")]
        [Xunit.TraitAttribute("FeatureTitle", "Observability Messages Per Second Metrics")]
        [Xunit.TraitAttribute("Description", "Validate End-to-End Flow Rate Metrics")]
        [Xunit.TraitAttribute("Category", "observability")]
        [Xunit.TraitAttribute("Category", "metrics")]
        [Xunit.TraitAttribute("Category", "flow")]
        [Xunit.TraitAttribute("Category", "end-to-end")]
        public async global::System.Threading.Tasks.Task ValidateEnd_To_EndFlowRateMetrics()
        {
            string[] tagsOfScenario = new string[] {
                    "observability",
                    "metrics",
                    "flow",
                    "end-to-end"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Validate End-to-End Flow Rate Metrics", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 29
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 30
    await testRunner.GivenAsync("LocalTesting infrastructure is running with observability enabled", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 31
    await testRunner.WhenAsync("I produce 800 messages to Kafka topic \"flow-test-input\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 32
    await testRunner.AndAsync("I start a Flink job to process messages", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 33
    await testRunner.AndAsync("I execute Temporal workflows", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 34
    await testRunner.ThenAsync("end-to-end flow rate metrics should show total throughput", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 35
    await testRunner.AndAsync("Kafka producer messages per second metrics should be greater than 0", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 36
    await testRunner.AndAsync("Flink job processing rate metrics should be recorded", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 37
    await testRunner.AndAsync("Temporal workflow execution rate metrics should be recorded", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 38
    await testRunner.AndAsync("Prometheus should be able to scrape all observability metrics", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Comprehensive Messages Per Second Metrics Validation")]
        [Xunit.TraitAttribute("FeatureTitle", "Observability Messages Per Second Metrics")]
        [Xunit.TraitAttribute("Description", "Comprehensive Messages Per Second Metrics Validation")]
        [Xunit.TraitAttribute("Category", "observability")]
        [Xunit.TraitAttribute("Category", "metrics")]
        [Xunit.TraitAttribute("Category", "comprehensive")]
        [Xunit.TraitAttribute("Category", "performance")]
        public async global::System.Threading.Tasks.Task ComprehensiveMessagesPerSecondMetricsValidation()
        {
            string[] tagsOfScenario = new string[] {
                    "observability",
                    "metrics",
                    "comprehensive",
                    "performance"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Comprehensive Messages Per Second Metrics Validation", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 41
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 42
    await testRunner.GivenAsync("LocalTesting infrastructure is running with observability enabled", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 43
    await testRunner.WhenAsync("I produce 2000 messages to Kafka topic \"comprehensive-test-input\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 44
    await testRunner.AndAsync("I start a Flink job to process messages", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 45
    await testRunner.AndAsync("I execute Temporal workflows", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 46
    await testRunner.ThenAsync("Kafka producer messages per second metrics should be greater than 0", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 47
    await testRunner.AndAsync("Flink job processing rate metrics should be recorded", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 48
    await testRunner.AndAsync("Temporal workflow execution rate metrics should be recorded", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 49
    await testRunner.AndAsync("end-to-end flow rate metrics should show total throughput", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 50
    await testRunner.AndAsync("Prometheus should be able to scrape all observability metrics", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, Xunit.IAsyncLifetime
        {
            
            async global::System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
            {
                await ObservabilityMessagesPerSecondMetricsFeature.FeatureSetupAsync();
            }
            
            async global::System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
            {
                await ObservabilityMessagesPerSecondMetricsFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
