// <auto-generated/>
#pragma warning disable
using global::System;
using global::System.CodeDom.Compiler;
using global::System.Collections.Generic;
using global::System.Globalization;
using global::System.Linq;
using global::System.Threading.Tasks;
using global::Reqnroll;

[assembly: global::Reqnroll.Plugin.IdeIntegration.Generator.IdeSingleFileGeneratorVersionAttribute("3.9.40.0")]

namespace FlinkDotNet.Aspire.IntegrationTests.Features
{
    [GeneratedCode("Reqnroll", "2.4.1.0")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.4.1.0")]
    [global::Reqnroll.Binding.StepArgumentTransformationAttribute("complex_logic_stress_test")]
    public partial class ComplexLogicStressTestFeature : global::Xunit.IClassFixture<global::Reqnroll.Infrastructure.TestAssemblyFixture>
    {
        private readonly global::Reqnroll.Infrastructure.ITestRunner testRunner;
        
        public ComplexLogicStressTestFeature()
        {
            this.testRunner = global::Reqnroll.TestInfrastructure.TestRunnerManager.GetTestRunner();
            global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "Features", "Complex Logic Stress Test - Multi-Stage Processing Pipeline", "  As a Flink.NET user\r\n  I want to process complex multi-stage data transformations under stress\r\n  So that I can validate complex business logic performance at scale", global::Reqnroll.ProgrammingLanguage.CSharp, featureInfo: new string[] {
                        "complex_logic_stress_test",
                        "multi_stage"});
            this.testRunner.OnFeatureStart(featureInfo);
        }
        
        [global::Xunit.FactAttribute()]
        [global::Xunit.TraitAttribute("FeatureTitle", "Complex Logic Stress Test - Multi-Stage Processing Pipeline")]
        [global::Xunit.TraitAttribute("Description", "Multi-Stage Data Processing Pipeline")]
        [global::Xunit.TraitAttribute("Category", "complex")]
        [global::Xunit.TraitAttribute("Category", "multi_stage")]
        [global::Xunit.TraitAttribute("Category", "business_logic")]
        public async System.Threading.Tasks.Task MultiStageDataProcessingPipeline()
        {
            string[] tagsOfScenario = new string[] {
                    "complex",
                    "multi_stage",
                    "business_logic"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Multi-Stage Data Processing Pipeline", null, tagsOfScenario, argumentsOfScenario, featureTags: new string[] {
                        "complex_logic_stress_test",
                        "multi_stage"});
            await this.testRunner.OnScenarioStartAsync(scenarioInfo);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.4.1.0")]
        public void FeatureSetup()
        {
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.4.1.0")]
        public void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public void Dispose()
        {
            this.testRunner.OnFeatureEnd();
            this.testRunner = null;
        }
    }
}
#pragma warning restore