// <auto-generated/>
#pragma warning disable
using global::System;
using global::System.CodeDom.Compiler;
using global::System.Collections.Generic;
using global::System.Globalization;
using global::System.Linq;
using global::System.Threading.Tasks;
using global::Reqnroll;

[assembly: global::Reqnroll.Plugin.IdeIntegration.Generator.IdeSingleFileGeneratorVersionAttribute("3.9.40.0")]

namespace FlinkDotNet.Aspire.IntegrationTests.Features
{
    [GeneratedCode("Reqnroll", "2.4.1.0")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.4.1.0")]
    [global::Reqnroll.Binding.StepArgumentTransformationAttribute("reliability_test")]
    public partial class ReliabilityTestFeature : global::Xunit.IClassFixture<global::Reqnroll.Infrastructure.TestAssemblyFixture>
    {
        private readonly global::Reqnroll.Infrastructure.ITestRunner testRunner;
        
        public ReliabilityTestFeature()
        {
            this.testRunner = global::Reqnroll.TestInfrastructure.TestRunnerManager.GetTestRunner();
            global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "Features", "Reliability Test - Fault Tolerance and Recovery with Actor-Based Resilience", "  As a Flink.NET user\r\n  I want to handle 10% failure rates with backpressure, rebalancing, and multi-cluster actor resilience\r\n  So that I can ensure system reliability under adverse conditions at enterprise scale", global::Reqnroll.ProgrammingLanguage.CSharp, featureInfo: new string[] {
                        "reliability_test",
                        "fault_tolerance"});
            this.testRunner.OnFeatureStart(featureInfo);
        }
        
        [global::Xunit.FactAttribute()]
        [global::Xunit.TraitAttribute("FeatureTitle", "Reliability Test - Fault Tolerance and Recovery with Actor-Based Resilience")]
        [global::Xunit.TraitAttribute("Description", "Handle 10% Message Failures with DLQ Processing")]
        [global::Xunit.TraitAttribute("Category", "reliability")]
        [global::Xunit.TraitAttribute("Category", "failure_injection")]
        [global::Xunit.TraitAttribute("Category", "dlq")]
        public async System.Threading.Tasks.Task Handle10MessageFailuresWithDLQProcessing()
        {
            string[] tagsOfScenario = new string[] {
                    "reliability",
                    "failure_injection",
                    "dlq"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Handle 10% Message Failures with DLQ Processing", null, tagsOfScenario, argumentsOfScenario, featureTags: new string[] {
                        "reliability_test",
                        "fault_tolerance"});
            await this.testRunner.OnScenarioStartAsync(scenarioInfo);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.4.1.0")]
        public void FeatureSetup()
        {
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.4.1.0")]
        public void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public void Dispose()
        {
            this.testRunner.OnFeatureEnd();
            this.testRunner = null;
        }
    }
}
#pragma warning restore