// <auto-generated/>
#pragma warning disable
using global::System;
using global::System.CodeDom.Compiler;
using global::System.Collections.Generic;
using global::System.Globalization;
using global::System.Linq;
using global::System.Threading.Tasks;
using global::Reqnroll;

[assembly: global::Reqnroll.Plugin.IdeIntegration.Generator.IdeSingleFileGeneratorVersionAttribute("3.9.40.0")]

namespace FlinkDotNet.Aspire.IntegrationTests.Features
{
    [GeneratedCode("Reqnroll", "2.4.1.0")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.4.1.0")]
    [global::Reqnroll.Binding.StepArgumentTransformationAttribute("stress_test")]
    public partial class StressTestFeature : global::Xunit.IClassFixture<global::Reqnroll.Infrastructure.TestAssemblyFixture>
    {
        private readonly global::Reqnroll.Infrastructure.ITestRunner testRunner;
        
        public StressTestFeature()
        {
            this.testRunner = global::Reqnroll.TestInfrastructure.TestRunnerManager.GetTestRunner();
            global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "Features", "Stress Test - High Throughput Message Processing with Multi-Cluster Orchestration", "  As a Flink.NET user\r\n  I want to process 1 million messages through both single clusters and multi-cluster orchestration\r\n  So that I can validate high-throughput streaming performance at enterprise scale", global::Reqnroll.ProgrammingLanguage.CSharp, featureInfo: new string[] {
                        "stress_test",
                        "high_throughput"});
            this.testRunner.OnFeatureStart(featureInfo);
        }
        
        [global::Xunit.FactAttribute()]
        [global::Xunit.TraitAttribute("FeatureTitle", "Stress Test - High Throughput Message Processing with Multi-Cluster Orchestration")]
        [global::Xunit.TraitAttribute("Description", "Process 1 Million Messages with FIFO and Exactly-Once Semantics")]
        [global::Xunit.TraitAttribute("Category", "stress")]
        [global::Xunit.TraitAttribute("Category", "fifo")]
        [global::Xunit.TraitAttribute("Category", "exactly_once")]
        public async System.Threading.Tasks.Task Process1MillionMessagesWithFIFOAndExactlyOnceSemantics()
        {
            string[] tagsOfScenario = new string[] {
                    "stress",
                    "fifo",
                    "exactly_once"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Process 1 Million Messages with FIFO and Exactly-Once Semantics", null, tagsOfScenario, argumentsOfScenario, featureTags: new string[] {
                        "stress_test",
                        "high_throughput"});
            await this.testRunner.OnScenarioStartAsync(scenarioInfo);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.4.1.0")]
        public void FeatureSetup()
        {
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.4.1.0")]
        public void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public void Dispose()
        {
            this.testRunner.OnFeatureEnd();
            this.testRunner = null;
        }
    }
}
#pragma warning restore