global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:8889']
    scrape_interval: 10s
    metrics_path: /metrics

  - job_name: 'flink-jobmanager'
    static_configs:
      - targets: ['flink-jobmanager:8081']
    metrics_path: /metrics
    scrape_interval: 10s

  - job_name: 'flink-taskmanager-1'
    static_configs:
      - targets: ['flink-taskmanager-1:8081']
    metrics_path: /metrics
    scrape_interval: 10s

  - job_name: 'flink-taskmanager-2'
    static_configs:
      - targets: ['flink-taskmanager-2:8081']
    metrics_path: /metrics
    scrape_interval: 10s

  - job_name: 'flink-taskmanager-3'
    static_configs:
      - targets: ['flink-taskmanager-3:8081']
    metrics_path: /metrics
    scrape_interval: 10s

  - job_name: 'localtesting-webapi'
    static_configs:
      - targets: ['localtesting-webapi:5000']
    metrics_path: /metrics
    scrape_interval: 10s