// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://www.reqnroll.net/).
//      Reqnroll Version:2.0.0.0
//      Reqnroll Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace LocalTesting.IntegrationTests.Features
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class ObservabilityMetricsValidationFeature : object, Xunit.IClassFixture<ObservabilityMetricsValidationFeature.FixtureData>, Xunit.IAsyncLifetime
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "Features", "Observability Metrics Validation", "  As a system administrator\n  I want to run the flow and see the metrics\n  So " +
                "that I can monitor system performance", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags);
        
        public ObservabilityMetricsValidationFeature(ObservabilityMetricsValidationFeature.FixtureData fixtureData, LocalTesting_IntegrationTests_XUnitAssemblyFixture assemblyFixture)
        {
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunner();
            global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "Features", "Observability Metrics Validation", "  As a system administrator\n  I want to run the flow and see the metrics\n  So " +
                    "that I can monitor system performance", global::Reqnroll.ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public void TestInitialize()
        {
        }
        
        public void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(testOutputHelper);
        }
        
        public void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual async global::System.Threading.Tasks.Task FeatureBackgroundAsync()
        {
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Simple Observability Flow")]
        [Xunit.TraitAttribute("FeatureTitle", "Observability Metrics Validation")]
        [Xunit.TraitAttribute("Description", "Simple Observability Flow")]
        [Xunit.TraitAttribute("Category", "observability")]
        [Xunit.TraitAttribute("Category", "metrics")]
        [Xunit.TraitAttribute("Category", "simple")]
        public async global::System.Threading.Tasks.Task SimpleObservabilityFlow()
        {
            string[] tagsOfScenario = new string[] {
                    "observability",
                    "metrics",
                    "simple"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Simple Observability Flow", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 8
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(tagsOfScenario) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.FeatureBackgroundAsync();
#line 9
    await testRunner.WhenAsync("I run the entire flow", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 10
    await testRunner.ThenAsync("we print the metrics to the console", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : global::System.IDisposable
        {
            
            public FixtureData()
            {
                ObservabilityMetricsValidationFeature.FeatureSetup();
            }
            
            void global::System.IDisposable.Dispose()
            {
                ObservabilityMetricsValidationFeature.FeatureTearDown();
            }
        }
        
        private Xunit.Abstractions.ITestOutputHelper testOutputHelper;
        
        public async global::System.Threading.Tasks.Task InitializeAsync()
        {
            await global::System.Threading.Tasks.Task.CompletedTask;
        }
        
        public async global::System.Threading.Tasks.Task DisposeAsync()
        {
            await global::System.Threading.Tasks.Task.CompletedTask;
        }
    }
}
#pragma warning restore
#endregion